defaults: &defaults
  app_name: Features
  noreply: noreply@fs-rails3-base.heroku.com
  host: localhost:3000

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  host: fs-rails3-base.heroku.com
