# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04235de3ce046facd858d70c9172cdbecd0310a29337ab070f513d14dc38026b3e18bc84f3aaacbb68957c578b2c33406f87faf63f03041d117112493f606e5c

test:
  secret_key_base: 3b821fcf01925f8d891446b78618b8258d77c32af0595b6434746802a74c3aab643b05f731c1e365415eab05b0907e4a699f2f74c378fd4a9747e5f89b38e37d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
